### PR TITLE
gone through team leader onboarding

### PR DESCRIPTION
**Pull request by bast**
typo fixes, slight shortening, reorganize where I thought it was helpful

### CODE REVIEW

**Comment by bast** [comment]
@samumantha

**Comment by samumantha** [comment]
👍

The thought about separating tips and tricks and background section was to separate it as "reading material", ie not to go through it during the onboarding. 

Would you go through all of this page during onboarding?

**Comment by bast** [comment]
During on-boarding I would skip few sections. We can also put the "background" back if that helps.

**Comment by samumantha** [comment]
Two comments/questions:

* The path ahead section is gone now? I thought it was nice to mention this for interested team leaders as we don't really have an official debriefing (where it would fit better?) Having gone that way, I found it helpful to know that there is different ways to get involved and that the project is open to it.

* the "please do not" section: if you want to have it as part of the onboarding I would get back the short version of this point from before my PR, not this very verbose version.

**Comment by samumantha** [comment]
> During on-boarding I would skip few sections. We can also put the "background" back if that helps.

We could put the sections that are skipped in bottom? 

I was trying to find a better place for the background section, but didn't find a good one. Should maybe not be here at all? 

Maybe there could be it's own background section in the manuals, where all the info on how CR workshops were done at certain point in time and background info on decisions made is presented?

**Comment by bast** [comment]
OK I will:
- bring back the path section
- try to shorten the "what we try to avoid"
- reorder with most important on top, what can be skipped on bottom

Later we can move the "background" stuff to some other pages but I am now out of time :-)

**Comment by samumantha** [comment]
Looks good and ready to merge

**Pull request merged**
