### PR TITLE
proposal on voting

### PR DESCRIPTION
**Pull request by rkdarst**
- This is a proposal for voting on actions via chat, using emojis and
  numbers.
- It's not something that exactly new, and this doesn't say this is
  how we actually decide anything.  Instead, it encourages people to
  give reactions that can be quantified, in the hopes that we can
  reduce uncertainly about making decisions.
- Review: everything, in particular is this a good way to present
  things?  Is it even worth presenting things?

### CODE REVIEW

**Review by bast — APPROVED** [review]
upvoted :-)

**Comment by rkdarst** [comment]
Emojis and LaTeX fail... interesting.

**Comment by bast** [comment]
Anything I can help with to get this fixed? Should we avoid the emoji?

**Comment by rkdarst** [comment]
Problem was emojis causing latex to fail.  Since then, I've learned that `xelatex` somehow can use emojis better by using system fonts, so was able to find this solution.

I think right now emojis would *not* be rendered.  This makes them rendered:
https://github.com/sphinx-contrib/emojicodes/pull/22/files
but I figured no need to add more dependencies, we can deal with this later if PDF is ever actually useful to someone...

**Pull request merged**
