### PR TITLE
add instructor and organization onboarding (short)

### PR DESCRIPTION
**Pull request by samumantha**
Added short info about instructors, material developer and organization to onboarding page. 

Feel free to edit, add or remove stuff. 

Soon: Will check instructor materials for correctness in current workshop format and add new page with more info for organizations.

### CODE REVIEW

**Comment by bast** [comment]
I suggest to decrease the image size for faster page load, less data use, and also smaller Git repo. We can keep big raw images in a separate repo.

**Comment by samumantha** [comment]
Ok, can do tomorrow 👌

**Comment by samumantha** [comment]
Source is here: https://github.com/coderefinery/presentations/blob/main/img/participate_organization.svg
Maybe it is also time to smoothen these images out "if there is time" someday. 
The new size better?

**Comment by samumantha** [comment]
Source is here: https://github.com/coderefinery/presentations/blob/main/img/participate_organization.svg
Maybe it is also time to smoothen these images out "if there is time" someday.
The new size better?

**Pull request merged**
