### PR TITLE
Restructure and shortening EL onboarding

### PR DESCRIPTION
**Pull request by samumantha**
- Created a background and tips and tricks section for additional information that people can read by themselves if needed
- Shortened/Merged the necessary stuff to go through during onboarding

Resolves Issue #239

### CODE REVIEW

**Comment by samumantha** [comment]
Now working on incorporating different types of teams and their specific needs/tips

**Review by bast — APPROVED** [review]
Nice that TLDR and Code of Conduct are on top.

**Comment by samumantha** [comment]
Let's say I am now done with my edits for now. I resolved to having the different team options from the image we also used in RSECon presentation, which also touches on #211 . It does not explicitly explain the different ways, but maybe enough for the onboarding?

Any comments, further ideas etc?

**Comment by samumantha** [comment]
Oh and I did not  build it yet (wrong computer), so currently just hope it looks ok.

**Comment by bast** [comment]
Thanks! I will merge now and I will read the rendered page and send my suggestions (if any) as follow-up PR.

**Pull request merged**
