### PR TITLE
Workshop roles and playbook cleanup

### PR DESCRIPTION
**Pull request by samumantha**
FYI that I am working on this currently.

Done:
* Fix grammar issues around recently replaced EL to team leader
* rename EL page to team-leaders and fix links
* add pages for registration and exercise coordinator as well as workshop marketing
* update links in playbook to new pages
* add old content of playbook to corresponding role pages.

I think this will need a few iterations and more context for the new role pages, but maybe it could be a starting point? 
I mainly thought of having pages for the background info of roles mentioned in the playbook. They could of course also just link to the role overview, let's check that possibility also!
Two roles that are now a bit unclear is the host and exercise coordinator. As their tasks overlap. Maybe we can figure this out from the upcoming workshop, how they should be called and their tasks distributed?

As usual feel free to edit and/or cherry-pick or disregard :)

### CODE REVIEW

**Comment by rkdarst** [comment]
Looks like good work reviewing everything!  It all looks good to me, at least as well as I have read and with the time I have now to read.

For workshop-playbook.md, maybe the whole checklist part could be put in triple-backquote quoting to protect from these warnings?

**Review by bast — APPROVED** [review]
Minor: is it team lead or team leader? For me "team lead" sounds better. No reason to change anything now though.

**Comment by bast** [comment]
> For workshop-playbook.md, maybe the whole checklist part could be put in triple-backquote quoting to protect from these warnings?

which warnings?

**Comment by rkdarst** [comment]
In the files-changed view, we see a `'myst' reference target not found:` for the MD links that don't have a target.  Since it's processed as a structured document, not opaque HTML links. (and incidentally for anyone interested, `myst` is a new role that myst-parser introduced that: tries to link to a document, if not tries to link to a reference, if not treats it as opaque HTML link and doesn't think about it - or something like that).  RST has a similar default you can choose but it treats it as a literal text if not found - though I always do "explicit is better than implicit")

**Review by rkdarst — APPROVED** [review]

**Comment by bast** [comment]
OK I will merge and look for warnings locally as follow-up. I want to merge this to also unblock the other PR.

**Pull request merged**
