### PR TITLE
Update from mar23 hackmd

### PR DESCRIPTION
**Pull request by MatiasJJ**
Still some roles could use those timing information

### CODE REVIEW

**Comment by bast** [comment]
I am reviewing ...

**Comment by MatiasJJ** [comment]
Thanks!
I still get this "Some checks were not successful" 🤷🏻‍♂️

**Comment by bast** [comment]
Spelling errors: https://github.com/coderefinery/manuals/actions/runs/4895521207/jobs/8741193733?pr=236

**Comment by bast** [comment]
Thanks! Merging. I will do a pass on the merged document.

**Pull request merged**
