### PR TITLE
Reorganization

### PR DESCRIPTION
**Pull request by samumantha**
draft, as it is currently in progress, but please check out new 'roles' page already and let me know what you think. 
Is such page useful?
Is it complete? - probably not
More known best practices?
Open for discussion :)

---

edit: now also some reorganizing done, but this needs more work.
Ie there is now two stream teaching pages which could be merged or so
Also the landing page texts need to be improved. 
For example: 
Exercise lead page could also be the intro page with the toc at bottom?
Instructor page could have some info on the team teaching (=easy access to teaching) as well as in CR one can teach what one knows best or want to learn more about, no need to know everything as there is multiple instructors plus many people helping with answering questions which go to hackmd and not directly to instructor.
Workshop organizers: This is usually CR staff, but can others join? What would be nice to fill with 'outside help',...

### CODE REVIEW

**Comment by rkdarst** [comment]
Looks good!  roles is what I was hoping for.

I hadn't even thought about the before/after the workshop roles.  Maybe the wider before/after roles could be on a different page (in the workshop organizer section).  Or should it be here?  I guess it can depend on how many roles there are, maybe one big overview is better (since it helps people move from "one workshop" to "organize the next")

Anyway, this is good.  I can also work on filling stuff out later.

(and it reminded me that I have been using the role "host" wrong.  I think your definition is the better one, I will update my other things.)

**Comment by samumantha** [comment]
Hmm, yes, true. 
Maybe it could also be split as it is now in the TOC?
during workshop: ex.lead, expert helper, instructor, hackmd help
workshop organization: host, broadcaster, etc..

**Comment by samumantha** [comment]
Done for today. Feel free to continue work on this branch

**Comment by samumantha** [comment]
One weird thing I noticed is that when I build it locally, on the main page the sidebar looks fine, but when clicking on any link, it changes . I do not quite understand why that happens

**Comment by bast** [comment]
> One weird thing I noticed is that when I build it locally, on the main page the sidebar looks fine, but when clicking on any link, it changes . I do not quite understand why that happens

I have that sometimes when changing navigation since it does not rebuild everything. What solves it for me: remove build folder, rebuild, refresh browser also.

**Review by rkdarst — APPROVED** [review]
This looks good to me, I suggest we merge it and iterate.  It's hard to know what's perfect until we see and explore it some, but it looks better at least.

**Comment by rkdarst** [comment]
I guess let's do this.

**Pull request merged**
