### PR TITLE
Instruct waiting list, fixes #34

### LINKED ISSUE #34: Instruct how to use Indico for "waiting list"
The lack of automated waiting list in Indico event registration system that we use was discussed here: 
https://docs.google.com/document/d/1vxeBmjoOWiJ8McFOzJpEbHcU1oWG5hsTiLAJFdW6HhE/

Document the conclusion of that discussion in the manuals.

### PR DESCRIPTION
**Pull request by juholehtonen**
Here is my sketch for the information about the waiting list that was missing in my opinion. 

I would have discussed this first in a PR as we teach but couldn't open a PR without some modifications in a branch.

I propose to migrate the corresponding google document into repo. Then I propose improvemts to manage a waiting list.

So I assumed a little bit here. Please feel free to reject this if eg. we don't want Indico manual into repo. This didn't take long. :)

### CODE REVIEW

**Comment by juholehtonen** [comment]
Note! Before merging and closing the issue, the current instructions should be removed: https://docs.google.com/document/d/1HGjegGW-rzWc1nktG3SVimylqbArGV41Q8UcrtVce7U/

**Comment by juholehtonen** [comment]
Also the documents referring to the above mentioned google document should be updated.

**Comment by bast** [comment]
As far as I can see:
- the Google doc has been ported and can be removed?
- it is referred to from https://github.com/coderefinery/manuals/blob/master/workshop-administration.md#other-documents-and-references?

Did I miss something?

**Comment by juholehtonen** [comment]
I think most important links to Indico guide are now updated. I didn't go through all our Google drive folders. I'll merge.

**Comment by bast** [comment]
Thanks! I have deleted the gdoc.

**Pull request merged**
