### PR TITLE
Suggestion: Merged EL subpages to one

### PR DESCRIPTION
**Pull request by samumantha**
* All subpages of Exercise leader material are merged to one for better overview. 
* BOR stuff related to instructor/Expert helper moved to their pages
* Links should all be fixed

I agree with what has been discussed in chat that for future onboarding it will be more helpful to have it all in one, if there is no apparant need to have it separate.

I tried to adjust texts a little bit for this, but likely future PRs are needed to fix some duplicates.

What do you think?

Good? Bad?

### CODE REVIEW

**Review by bast — APPROVED** [review]
Thanks!

**Comment by bast** [comment]
Any help needed with the conflicts?

**Comment by samumantha** [comment]
Yes I do not quite understand the conflicts?

**Comment by bast** [comment]
This PR deletes files which have evolved upstream. But there are also some conflicts that are not just file deletion. In short: things have been modified in the same place in two different ways.

If we merge, will we break any links in this email: https://github.com/coderefinery/2022-03-22-workshop/issues/20 ?

**Comment by samumantha** [comment]
no, the link in email stayed same

**Comment by bast** [comment]
OK I am looking at the conflicts. Extremely little time here but hopefully I will manage.

**Comment by bast** [comment]
Sorry, out of time. Too complicated conflict. I will have to fix it later or somebody else needs to.

**Comment by rkdarst** [comment]
Is it easier to re-implement the moves/copy other modifications onto the current version?

**Comment by samumantha** [comment]
Sorry for being so late with this. Wednesday came sooner than expected. 

I can also do it but would need some guidance on how to deal with the deletion conflicts.

**Comment by rkdarst** [comment]
Personally, when I see something that has been done on an old version and there are too many conflicts, I would make a new branch and redo the most important changes there.  In effect, someone needs to look at all the individual parts anyway, and doing it from scratch is less pain, I think.

**Comment by bast** [comment]
I might be easier to re-apply on top of latest master. It's probably not too difficult to decide for you two what to keep but for me since I did not write any of the two sides I would have to diff and compare what happened and I am out of time until around 5 pm.

**Comment by samumantha** [comment]
To understand and do better next time: i applied my changes to an outdated copy of master branch? (At least I intended to update it before starting to do changes, but maybe that went wrong :( ) and that is creating the big issues now?

**Comment by rkdarst** [comment]
Correct.  Don't worry, it has happened to all of us many times!

**Comment by samumantha** [comment]
Ok, I'll do that instead and close this PR

**Pull request closed without merging**
