### PR TITLE
Add sphinx project to manuals

### PR DESCRIPTION
**Pull request by rkdarst**
- Just a draft, not complete
- Should this be continued?  It seems reasonable, and doesn't require
  changing much markdown (but does require fixing links, where they
  are not currently relative) - this is good anyway.

### CODE REVIEW

**Comment by rkdarst** [comment]
This is ready for initial review, before I go and do the rest of the work to make it

**Comment by rkdarst** [comment]
I think this is ready to go.  The deployment to gh-pages is untested, and I'd like to change the front page from md to rst (because that toctree directive is nice), using code fences here doesn't look so good.  I'm leaving it as-is so that people can see how it works.

Overall sphinx + myst_parser here was very easy - no major conversion needed, regular markdown works fine, other than a bit of work to make links properly relative or not.  I expect actual lessons to be harder, because of extensive use of the callout blocks.

Follow-ups will include rearrangement and formatting work (this is minimal to make it compile reasonably).

To check: is this a  good idea?  GH-actions looks ok?  Most of the rest of formatting stuff can be follow-ups.

**Comment by bast** [comment]
I think Sphinx is a good choice for the manual. From my perspective this can be merged and we iterate from there.

**Comment by rkdarst** [comment]
I consider this mergeable, but I think I will need an admin's help to toggle gh-pages off and on, to make it actually render the first time.  Then, it's automatic.

Also, if it works, to set the website in the repo description.

**Comment by rkdarst** [comment]
For merging this, I propose:
- someone merges
- wait a while, verify gh-pages branch is built, if not fix it.
- verify that it doesn't appear on gh-pages
- check out the gh-pages branch, make a trivial change, push manually.  See if that kicks it into making a gh-pages deployment.

The "bad case" is:
- you have to go to settings, and flip it off and on again, to make it deploy the first time (future times work)

**Pull request merged**
